server:
  port: 7000


spring:
  datasource:
    url: jdbc:postgresql://ep-raspy-haze-a5r2jrux.us-east-2.aws.neon.tech/control?user=control_owner&password=pd8laR5PsjGH&sslmode=require
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        jdbc:
            time_zone: UTC
        show_sql: true
  output:
    ansi:
      enabled: Always
logging:
  level:
    br:
      com:
        ronna: DEBUG